/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'], // Fallback for Domaine/Favorit
        mono: ['Geist Mono', 'JetBrains Mono', 'monospace'],
      },
      colors: {
        resend: {
          primary: '#fcfdff',
          'primary-on': '#000000',
          ink: '#fcfdff',
          body: 'rgba(252,253,255,0.86)',
          charcoal: 'rgba(252,253,255,0.7)',
          mute: '#a1a4a5',
          ash: '#888e90',
          stone: '#464a4d',
          'on-light': '#000000',
          'on-light-mute': 'rgba(0,0,51,0.7)',
          canvas: '#000000',
          'surface-card': '#0a0a0c',
          'surface-elevated': '#101012',
          'surface-deep': '#06060a',
          hairline: 'rgba(255,255,255,0.06)',
          'hairline-strong': 'rgba(255,255,255,0.14)',
          'divider-soft': 'rgba(255,255,255,0.04)',
          'accent-orange': '#ff801f',
          'accent-orange-glow': 'rgba(255,89,0,0.22)',
          'accent-yellow': '#ffc53d',
          'accent-blue': '#3b9eff',
          'accent-blue-glow': 'rgba(0,117,255,0.34)',
          'accent-green': '#11ff99',
          'accent-green-glow': 'rgba(34,255,153,0.18)',
          'accent-red': '#ff2047',
          'accent-red-glow': 'rgba(255,32,71,0.34)',
          link: '#3b9eff',
          'surface-light': '#f1f7fe',
        },
      },
      borderRadius: {
        'resend-none': '0px',
        'resend-xs': '4px',
        'resend-sm': '6px',
        'resend-md': '8px',
        'resend-lg': '12px',
        'resend-xl': '16px',
        'resend-full': '9999px',
      },
      spacing: {
        'resend-section': '96px',
        'resend-band': '128px',
      },
      letterSpacing: {
        'resend-tight': '-0.96px',
        'resend-tighter': '-2.8px',
        'resend-button': '0.35px',
      },
    },
  },
  plugins: [],
};
